### ISSUE TITLE
it doesn't work on Python3.5 

### ISSUE THREAD

**Issue by moskomule** [attardi/wikiextractor#83]
I'm using it on both 2.7 and 3.5 but on Python3.5, an AttributionError occurs.

```
Traceback (most recent call last):
  File "/home/user/documents/wikipedia/wikiextractor/WikiExtractor.py", line 3044, in <module>
    main()
  File "/home/user/documents/wikipedia/wikiextractor/WikiExtractor.py", line 3040, in main
    args.compress, args.processes)
  File "/home/user/documents/wikipedia/wikiextractor/WikiExtractor.py", line 2707, in process_dump
    line = line.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
```

on 2.7, no problem. Thank you.

**Comment by supyoung** [comment]
the py can't work on python3. First of all, the import packages like cStringIO, htmlentitydefs had been remove from python3 maybe from python 3.4. Just a remind.

**Comment by wilhelmhagg** [comment]
I just tried on python 3.5.2 and the only issue i found was the decode, which is no longer there in python3 since by default all strings are encoded in utf-8. Adding the following condition to the two decode lines in the script solved the issue for me:

if PY2:
        line = line.decode('utf-8')

**Comment by kefir-** [comment]
I can confirm that this patch, as suggested by @wilhelmhagg, fixed my WikiExtractor.py on Python 3.5.2. Sorry for not making this a pull request...

$ git diff
diff --git a/WikiExtractor.py b/WikiExtractor.py
index e46b102..5f8f0ed 100755
--- a/WikiExtractor.py
+++ b/WikiExtractor.py
@@ -2637,7 +2637,8 @@ def pages_from(input):
     redirect = False
     title = None
     for line in input:
-        line = line.decode('utf-8')
+        if PY2:
+            line = line.decode('utf-8')
         if '<' not in line:  # faster than doing re.search()
             if inText:
                 page.append(line)
@@ -2707,7 +2708,8 @@ def process_dump(input_file, template_file, out_file, file_size, file_compress,
 
     # collect siteinfo
     for line in input:
-        line = line.decode('utf-8')
+        if PY2:
+            line = line.decode('utf-8')
         m = tagRE.search(line)
         if not m:
             continue

**Comment by attardi** [comment]
I committed the changes.
Thank you.
